apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name:
          image: bhaktijkoli/k3s-demo-writer
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: writer-1-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name:
          image: bhaktijkoli/k3s-demo-writer
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: writer-2-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name:
          image: bhaktijkoli/k3s-demo-reader
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: reader-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reader-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/koireader/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writer-1-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/koireader/data/r1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writer-2-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/koireader/data/r2
