apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name: writer-1
          image: bhaktijkoli/k3s-demo-writer
          env:
            - name: WRITE_PATH
              value: /app/data
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: writer-1-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name: writer-2
          image: bhaktijkoli/k3s-demo-writer
          env:
            - name: WRITE_PATH
              value: /app/data
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: writer-2-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
        - name: reader
          image: bhaktijkoli/k3s-demo-reader
          env:
            - name: READ_PATH
              value: /app/data
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: reader-pvc