apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reader-pvc
  labels:
    app: k3s-demo
spec:
  volumeName: reader-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writer-1-pvc
  labels:
    app: k3s-demo
spec:
  volumeName: writer-1-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writer-2-pvc
  labels:
    app: k3s-demo
spec:
  volumeName: writer-2-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi